name: EXPorter
version: '${project.version}'
main: net.aerh.exporter.EXPorterPlugin
api-version: '1.20'
commands:
  xpwithdraw:
    description: Withdraws the specified amount of experience from your experience levels.
    usage: /xpwithdraw <amount>
    aliases: [xpw, withdrawxp, withdrawexperience]
    permission: exporter.withdraw
  exporter:
    description: Main command for the EXPorter plugin.
    usage: /exporter <subcommand>
    aliases: [xporter]
    permission: exporter.use
